### ISSUE TITLE
Getting exception when using allure.description

### ISSUE THREAD

**Issue by mathewkuruvila** [ryparker/jest-circus-allure-environment#70]
**Describe the bug**
When used allure.description in jest test cases getting below exception

  ● DemoTest1 › DemoTest 1.1 regressoin

    RangeError: Maximum call stack size exceeded

      at JestAllureInterface.description (node_modules/jest-circus-allure-environment/src/jest-allure-interface.ts:137:20)
      at JestAllureInterface.description (node_modules/jest-circus-allure-environment/src/jest-allure-interface.ts:138:8)
      at JestAllureInterface.description (node_modules/jest-circus-allure-environment/src/jest-allure-interface.ts:138:8)
      at JestAllureInterface.description (node_modules/jest-circus-allure-environment/src/jest-allure-interface.ts:138:8)
      at JestAllureInterface.description (node_modules/jest-circus-allure-environment/src/jest-allure-interface.ts:138:8)

**To Reproduce**

`it("DemoTest 1.1 regressoin", async () => {

        await new Promise(resolve => setTimeout(resolve, 4000));

        console.log("DemoTest 1.1")

        console.log("process.env.NODE_BRO " + process.env.NODE_BRO)
        console.log("process.env.NODE_ENV " + process.env.NODE_ENV)

        allure.logStep('step DemoTest 1.1 water '+ process.env.NODE_BRO);
        allure.logStep('step DemoTest 1.1'+ process.env.NODE_ENV);

        allure.description("description Step DemoTest 1.1");
    })
`
    
package.json

  "devDependencies": {
    "jest": "^26.4.2",
    "jest-circus": "^26.4.2",
    "jest-circus-allure-environment": "^0.11.2"
  }

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser 
 - Version

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ryparker** [comment]
Thanks for opening a ticket. It looks like the allure.description() method was not fetching the currently active test case before applying the description. I've made a fix for this and [wrote a test that provides an example of how it can be used here.](https://github.com/ryparker/jest-circus-allure-environment/blob/master/__tests__/allure-api/description.test.js)

BTW the recommended way to add a description to a test case is to use docBlock comments since these have no chance of interfering with your test code. 

Example:

```TS
test('does something important, when triggered by user', () => {
  /** This is my description that will appear on the Allure report.
   */

  ...
})
```

[Documentation](https://github.com/ryparker/jest-circus-allure-environment#-descriptions)

**Comment by mathewkuruvila** [comment]
Thanks Mate

**Comment by ryparker** [comment]
No problem 👍🏻
